name: mfoc build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc-5, gcc-6, gcc-7, gcc-8]
        platform: [linux/amd64, linux/arm64, linux/386, linux/arm/v7]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          pull: true
          build-args: |
            COMPILER=${{ matrix.compiler }}
          platforms: ${{ matrix.platform }}
